// Real archviz portfolio data — extracted from the source bundle.
// 26 projects across 10 categories.
// 233 media items total.

export type CategoryId =
  | "01_APARTMENT"
  | "02_MIXED_USE"
  | "03_COMPETITION"
  | "04_HOTEL RESORT"
  | "05_MALL"
  | "06_OFFICE"
  | "07_RESDENCE"
  | "08_LANDSCAPE"
  | "09_PROPOSAL"
  | "11_CAFE ANDRESTAURANT";

export interface Category {
  id: CategoryId;
  number: string;
  label: string;
}

export const CATEGORIES: Category[] = [
  { id: "01_APARTMENT", number: "01", label: "Apartment" },
  { id: "02_MIXED_USE", number: "02", label: "Mixed Use" },
  { id: "03_COMPETITION", number: "03", label: "Competition" },
  { id: "04_HOTEL RESORT", number: "04", label: "Hotel & Resort" },
  { id: "05_MALL", number: "05", label: "Mall" },
  { id: "06_OFFICE", number: "06", label: "Office" },
  { id: "07_RESDENCE", number: "07", label: "Residence" },
  { id: "08_LANDSCAPE", number: "08", label: "Landscape" },
  { id: "09_PROPOSAL", number: "09", label: "Proposal" },
  { id: "11_CAFE ANDRESTAURANT", number: "11", label: "Cafe & Restaurant" },
];

export interface MediaItem {
  src: string;
  isVideo: boolean;
  fileName: string;
}

export interface Project {
  id: string;
  category: CategoryId;
  categoryNumber: string;
  title: string;
  year: string;
  location: string;
  scale: string;
  media: MediaItem[];
}

export const PROJECTS: Project[] = [
  {
    id: "ataklti",
    category: "01_APARTMENT",
    categoryNumber: "01",
    title: "ATAKLTI",
    year: "2024",
    location: "Addis Ababa, ET",
    scale: "Residential Tower",
    media: [
    { src: "/projects/01_APARTMENT/ATAKLTI/01 (3).webp", isVideo: false, fileName: "01 (3).webp" },
    { src: "/projects/01_APARTMENT/ATAKLTI/01 (10).webp", isVideo: false, fileName: "01 (10).webp" },
    ],
  },
  {
    id: "dsl-bole",
    category: "01_APARTMENT",
    categoryNumber: "01",
    title: "DSL BOLE",
    year: "2024",
    location: "Bole, Addis Ababa",
    scale: "Residential — Aerial Animation",
    media: [
    { src: "/projects/01_APARTMENT/DSL BOLE/aeriaanimationlafter.mp4", isVideo: true, fileName: "aeriaanimationlafter.mp4" },
    { src: "/projects/01_APARTMENT/DSL BOLE/aerialanimatiobefore.mp4", isVideo: true, fileName: "aerialanimatiobefore.mp4" },
    ],
  },
  {
    id: "esknder-apt",
    category: "01_APARTMENT",
    categoryNumber: "01",
    title: "ESKNDER APT",
    year: "2024",
    location: "Addis Ababa, ET",
    scale: "Apartment Interior",
    media: [
    { src: "/projects/01_APARTMENT/ESKNDER APT/01 (4).webp", isVideo: false, fileName: "01 (4).webp" },
    { src: "/projects/01_APARTMENT/ESKNDER APT/01 (5).webp", isVideo: false, fileName: "01 (5).webp" },
    { src: "/projects/01_APARTMENT/ESKNDER APT/Scene 83_3.webp", isVideo: false, fileName: "Scene 83_3.webp" },
    { src: "/projects/01_APARTMENT/ESKNDER APT/Scene 100.webp", isVideo: false, fileName: "Scene 100.webp" },
    { src: "/projects/01_APARTMENT/ESKNDER APT/Scene 102.webp", isVideo: false, fileName: "Scene 102.webp" },
    { src: "/projects/01_APARTMENT/ESKNDER APT/Shot 3.mp4", isVideo: true, fileName: "Shot 3.mp4" },
    { src: "/projects/01_APARTMENT/ESKNDER APT/Shot 4.mp4", isVideo: true, fileName: "Shot 4.mp4" },
    { src: "/projects/01_APARTMENT/ESKNDER APT/Shot 8.mp4", isVideo: true, fileName: "Shot 8.mp4" },
    ],
  },
  {
    id: "hugo",
    category: "01_APARTMENT",
    categoryNumber: "01",
    title: "HUGO",
    year: "2024",
    location: "Addis Ababa, ET",
    scale: "Apartment Interior",
    media: [
    { src: "/projects/01_APARTMENT/HUGO/01 (4).webp", isVideo: false, fileName: "01 (4).webp" },
    { src: "/projects/01_APARTMENT/HUGO/01 (6).webp", isVideo: false, fileName: "01 (6).webp" },
    { src: "/projects/01_APARTMENT/HUGO/01 (8).webp", isVideo: false, fileName: "01 (8).webp" },
    { src: "/projects/01_APARTMENT/HUGO/01 (9).webp", isVideo: false, fileName: "01 (9).webp" },
    { src: "/projects/01_APARTMENT/HUGO/01 (11).webp", isVideo: false, fileName: "01 (11).webp" },
    { src: "/projects/01_APARTMENT/HUGO/bath.webp", isVideo: false, fileName: "bath.webp" },
    { src: "/projects/01_APARTMENT/HUGO/Living room3_1.webp", isVideo: false, fileName: "Living room3_1.webp" },
    { src: "/projects/01_APARTMENT/HUGO/Living room8_1.webp", isVideo: false, fileName: "Living room8_1.webp" },
    { src: "/projects/01_APARTMENT/HUGO/OVER ALL4(1)_upscale_1.webp", isVideo: false, fileName: "OVER ALL4(1)_upscale_1.webp" },
    ],
  },
  {
    id: "jambo",
    category: "01_APARTMENT",
    categoryNumber: "01",
    title: "JAMBO",
    year: "2024",
    location: "Addis Ababa, ET",
    scale: "Apartment Exterior",
    media: [
    { src: "/projects/01_APARTMENT/JAMBO/D5_Image_20240301_171459.webp", isVideo: false, fileName: "D5_Image_20240301_171459.webp" },
    ],
  },
  {
    id: "mule-apt",
    category: "01_APARTMENT",
    categoryNumber: "01",
    title: "MULE APT",
    year: "2024",
    location: "Addis Ababa, ET",
    scale: "Apartment — Aerial Comparison",
    media: [
    { src: "/projects/01_APARTMENT/MULE APT/01 (1).webp", isVideo: false, fileName: "01 (1).webp" },
    { src: "/projects/01_APARTMENT/MULE APT/aerialstaticafter.webp", isVideo: false, fileName: "aerialstaticafter.webp" },
    ],
  },
  {
    id: "yahhar-real-estate",
    category: "01_APARTMENT",
    categoryNumber: "01",
    title: "YAHHAR REAL ESTATE",
    year: "2024",
    location: "Addis Ababa, ET",
    scale: "Real Estate Masterplan",
    media: [
    { src: "/projects/01_APARTMENT/YAHHAR REAL ESTATE/01 (1).webp", isVideo: false, fileName: "01 (1).webp" },
    { src: "/projects/01_APARTMENT/YAHHAR REAL ESTATE/01 (12).webp", isVideo: false, fileName: "01 (12).webp" },
    { src: "/projects/01_APARTMENT/YAHHAR REAL ESTATE/01 (13).webp", isVideo: false, fileName: "01 (13).webp" },
    { src: "/projects/01_APARTMENT/YAHHAR REAL ESTATE/01 (15).webp", isVideo: false, fileName: "01 (15).webp" },
    { src: "/projects/01_APARTMENT/YAHHAR REAL ESTATE/01 (23).webp", isVideo: false, fileName: "01 (23).webp" },
    { src: "/projects/01_APARTMENT/YAHHAR REAL ESTATE/01 (38).webp", isVideo: false, fileName: "01 (38).webp" },
    { src: "/projects/01_APARTMENT/YAHHAR REAL ESTATE/01 (44).webp", isVideo: false, fileName: "01 (44).webp" },
    { src: "/projects/01_APARTMENT/YAHHAR REAL ESTATE/01 (45).webp", isVideo: false, fileName: "01 (45).webp" },
    { src: "/projects/01_APARTMENT/YAHHAR REAL ESTATE/01 (46).webp", isVideo: false, fileName: "01 (46).webp" },
    { src: "/projects/01_APARTMENT/YAHHAR REAL ESTATE/2.mp4", isVideo: true, fileName: "2.mp4" },
    { src: "/projects/01_APARTMENT/YAHHAR REAL ESTATE/03.mp4", isVideo: true, fileName: "03.mp4" },
    { src: "/projects/01_APARTMENT/YAHHAR REAL ESTATE/D5_Scene 5 1_20231221_125609.webp", isVideo: false, fileName: "D5_Scene 5 1_20231221_125609.webp" },
    ],
  },
  {
    id: "mnrc",
    category: "02_MIXED_USE",
    categoryNumber: "02",
    title: "MNRC",
    year: "2024",
    location: "Addis Ababa, ET",
    scale: "Mixed-Use Development",
    media: [
    { src: "/projects/02_MIXED_USE/MNRC/01 (1).webp", isVideo: false, fileName: "01 (1).webp" },
    { src: "/projects/02_MIXED_USE/MNRC/01 (14).webp", isVideo: false, fileName: "01 (14).webp" },
    { src: "/projects/02_MIXED_USE/MNRC/Clip 2.mp4", isVideo: true, fileName: "Clip 2.mp4" },
    { src: "/projects/02_MIXED_USE/MNRC/Clip 3_1.mp4", isVideo: true, fileName: "Clip 3_1.mp4" },
    { src: "/projects/02_MIXED_USE/MNRC/FLY_11.mp4", isVideo: true, fileName: "FLY_11.mp4" },
    { src: "/projects/02_MIXED_USE/MNRC/food court.mp4", isVideo: true, fileName: "food court.mp4" },
    { src: "/projects/02_MIXED_USE/MNRC/MNRC POOL.mp4", isVideo: true, fileName: "MNRC POOL.mp4" },
    { src: "/projects/02_MIXED_USE/MNRC/OUT_0.1.mp4", isVideo: true, fileName: "OUT_0.1.mp4" },
    { src: "/projects/02_MIXED_USE/MNRC/Shot 1(5).mp4", isVideo: true, fileName: "Shot 1(5).mp4" },
    { src: "/projects/02_MIXED_USE/MNRC/Shot 3 (2).mp4", isVideo: true, fileName: "Shot 3 (2).mp4" },
    { src: "/projects/02_MIXED_USE/MNRC/Shot 3.mp4", isVideo: true, fileName: "Shot 3.mp4" },
    { src: "/projects/02_MIXED_USE/MNRC/Shot 5 (2).mp4", isVideo: true, fileName: "Shot 5 (2).mp4" },
    { src: "/projects/02_MIXED_USE/MNRC/Shot 5.mp4", isVideo: true, fileName: "Shot 5.mp4" },
    { src: "/projects/02_MIXED_USE/MNRC/TOUR TO GROUND_2.mp4", isVideo: true, fileName: "TOUR TO GROUND_2.mp4" },
    { src: "/projects/02_MIXED_USE/MNRC/WALK 02.mp4", isVideo: true, fileName: "WALK 02.mp4" },
    { src: "/projects/02_MIXED_USE/MNRC/WALK_04.mp4", isVideo: true, fileName: "WALK_04.mp4" },
    { src: "/projects/02_MIXED_USE/MNRC/WALK_05.mp4", isVideo: true, fileName: "WALK_05.mp4" },
    { src: "/projects/02_MIXED_USE/MNRC/WALK_07.mp4", isVideo: true, fileName: "WALK_07.mp4" },
    ],
  },
  {
    id: "omar",
    category: "02_MIXED_USE",
    categoryNumber: "02",
    title: "OMAR",
    year: "2024",
    location: "Addis Ababa, ET",
    scale: "Mixed-Use — Full Visualization Set",
    media: [
    { src: "/projects/02_MIXED_USE/OMAR/01 (13).webp", isVideo: false, fileName: "01 (13).webp" },
    { src: "/projects/02_MIXED_USE/OMAR/01 (25).webp", isVideo: false, fileName: "01 (25).webp" },
    { src: "/projects/02_MIXED_USE/OMAR/01 (26).webp", isVideo: false, fileName: "01 (26).webp" },
    { src: "/projects/02_MIXED_USE/OMAR/01 (27).webp", isVideo: false, fileName: "01 (27).webp" },
    { src: "/projects/02_MIXED_USE/OMAR/01 (28).webp", isVideo: false, fileName: "01 (28).webp" },
    { src: "/projects/02_MIXED_USE/OMAR/01 (29).webp", isVideo: false, fileName: "01 (29).webp" },
    { src: "/projects/02_MIXED_USE/OMAR/01 (30).webp", isVideo: false, fileName: "01 (30).webp" },
    { src: "/projects/02_MIXED_USE/OMAR/01 (31).webp", isVideo: false, fileName: "01 (31).webp" },
    { src: "/projects/02_MIXED_USE/OMAR/01 (32).webp", isVideo: false, fileName: "01 (32).webp" },
    { src: "/projects/02_MIXED_USE/OMAR/01 (33).webp", isVideo: false, fileName: "01 (33).webp" },
    { src: "/projects/02_MIXED_USE/OMAR/01 (34).webp", isVideo: false, fileName: "01 (34).webp" },
    { src: "/projects/02_MIXED_USE/OMAR/01 (35).webp", isVideo: false, fileName: "01 (35).webp" },
    { src: "/projects/02_MIXED_USE/OMAR/01 (36).webp", isVideo: false, fileName: "01 (36).webp" },
    { src: "/projects/02_MIXED_USE/OMAR/FLY_01.mp4", isVideo: true, fileName: "FLY_01.mp4" },
    { src: "/projects/02_MIXED_USE/OMAR/FLY_02.mp4", isVideo: true, fileName: "FLY_02.mp4" },
    { src: "/projects/02_MIXED_USE/OMAR/FLY_03.mp4", isVideo: true, fileName: "FLY_03.mp4" },
    { src: "/projects/02_MIXED_USE/OMAR/FLY_04.mp4", isVideo: true, fileName: "FLY_04.mp4" },
    { src: "/projects/02_MIXED_USE/OMAR/FLY_05.mp4", isVideo: true, fileName: "FLY_05.mp4" },
    { src: "/projects/02_MIXED_USE/OMAR/FLY_06.mp4", isVideo: true, fileName: "FLY_06.mp4" },
    { src: "/projects/02_MIXED_USE/OMAR/FLY_07.mp4", isVideo: true, fileName: "FLY_07.mp4" },
    { src: "/projects/02_MIXED_USE/OMAR/FLY_08.mp4", isVideo: true, fileName: "FLY_08.mp4" },
    { src: "/projects/02_MIXED_USE/OMAR/FLY_09.mp4", isVideo: true, fileName: "FLY_09.mp4" },
    { src: "/projects/02_MIXED_USE/OMAR/image26.webp", isVideo: false, fileName: "image26.webp" },
    { src: "/projects/02_MIXED_USE/OMAR/image27.webp", isVideo: false, fileName: "image27.webp" },
    { src: "/projects/02_MIXED_USE/OMAR/Shot 5.mp4", isVideo: true, fileName: "Shot 5.mp4" },
    { src: "/projects/02_MIXED_USE/OMAR/Shot 27.mp4", isVideo: true, fileName: "Shot 27.mp4" },
    { src: "/projects/02_MIXED_USE/OMAR/Shot 30.mp4", isVideo: true, fileName: "Shot 30.mp4" },
    { src: "/projects/02_MIXED_USE/OMAR/Shot 31.mp4", isVideo: true, fileName: "Shot 31.mp4" },
    { src: "/projects/02_MIXED_USE/OMAR/Shot 33.mp4", isVideo: true, fileName: "Shot 33.mp4" },
    { src: "/projects/02_MIXED_USE/OMAR/Shot 35.mp4", isVideo: true, fileName: "Shot 35.mp4" },
    { src: "/projects/02_MIXED_USE/OMAR/Shot 37.mp4", isVideo: true, fileName: "Shot 37.mp4" },
    { src: "/projects/02_MIXED_USE/OMAR/Shot 38.mp4", isVideo: true, fileName: "Shot 38.mp4" },
    { src: "/projects/02_MIXED_USE/OMAR/Shot 39.mp4", isVideo: true, fileName: "Shot 39.mp4" },
    { src: "/projects/02_MIXED_USE/OMAR/Shot 42(1).mp4", isVideo: true, fileName: "Shot 42(1).mp4" },
    { src: "/projects/02_MIXED_USE/OMAR/Shot 44.mp4", isVideo: true, fileName: "Shot 44.mp4" },
    { src: "/projects/02_MIXED_USE/OMAR/Shot 45.mp4", isVideo: true, fileName: "Shot 45.mp4" },
    { src: "/projects/02_MIXED_USE/OMAR/Shot 56.mp4", isVideo: true, fileName: "Shot 56.mp4" },
    { src: "/projects/02_MIXED_USE/OMAR/Shot 57.mp4", isVideo: true, fileName: "Shot 57.mp4" },
    ],
  },
  {
    id: "synergy",
    category: "03_COMPETITION",
    categoryNumber: "03",
    title: "SYNERGY",
    year: "2023",
    location: "Competition",
    scale: "Concept Design",
    media: [
    { src: "/projects/03_COMPETITION/SYNERGY/01 (40).webp", isVideo: false, fileName: "01 (40).webp" },
    { src: "/projects/03_COMPETITION/SYNERGY/Shot 27_00000000.webp", isVideo: false, fileName: "Shot 27_00000000.webp" },
    ],
  },
  {
    id: "ake-hotel-resort",
    category: "04_HOTEL RESORT",
    categoryNumber: "04",
    title: "AKE HOTEL RESORT",
    year: "2024",
    location: "Resort",
    scale: "Hotel & Resort Animation",
    media: [
    { src: "/projects/04_HOTEL RESORT/AKE HOTEL RESORT/01.mp4", isVideo: true, fileName: "01.mp4" },
    { src: "/projects/04_HOTEL RESORT/AKE HOTEL RESORT/D5 Render 2026-01-30 14-43-43.mp4", isVideo: true, fileName: "D5 Render 2026-01-30 14-43-43.mp4" },
    { src: "/projects/04_HOTEL RESORT/AKE HOTEL RESORT/Shot 4.mp4", isVideo: true, fileName: "Shot 4.mp4" },
    { src: "/projects/04_HOTEL RESORT/AKE HOTEL RESORT/Shot 13.mp4", isVideo: true, fileName: "Shot 13.mp4" },
    { src: "/projects/04_HOTEL RESORT/AKE HOTEL RESORT/Shot 14.mp4", isVideo: true, fileName: "Shot 14.mp4" },
    { src: "/projects/04_HOTEL RESORT/AKE HOTEL RESORT/Shot 15.mp4", isVideo: true, fileName: "Shot 15.mp4" },
    ],
  },
  {
    id: "mnrc-mall",
    category: "05_MALL",
    categoryNumber: "05",
    title: "MNRC MALL",
    year: "2024",
    location: "Addis Ababa, ET",
    scale: "Retail Mall Animation",
    media: [
    { src: "/projects/05_MALL/MNRC MALL/food court.mp4", isVideo: true, fileName: "food court.mp4" },
    { src: "/projects/05_MALL/MNRC MALL/OTHER SCENEE.mp4", isVideo: true, fileName: "OTHER SCENEE.mp4" },
    { src: "/projects/05_MALL/MNRC MALL/OUT_0.1.mp4", isVideo: true, fileName: "OUT_0.1.mp4" },
    { src: "/projects/05_MALL/MNRC MALL/Shot 2.mp4", isVideo: true, fileName: "Shot 2.mp4" },
    { src: "/projects/05_MALL/MNRC MALL/Shot 3.mp4", isVideo: true, fileName: "Shot 3.mp4" },
    ],
  },
  {
    id: "yeka",
    category: "05_MALL",
    categoryNumber: "05",
    title: "YEKA",
    year: "2024",
    location: "Addis Ababa, ET",
    scale: "Mall — Aerial & Walkthrough",
    media: [
    { src: "/projects/05_MALL/YEKA/01 (14).webp", isVideo: false, fileName: "01 (14).webp" },
    { src: "/projects/05_MALL/YEKA/D5_Shot 1_20240405_133217.mp4", isVideo: true, fileName: "D5_Shot 1_20240405_133217.mp4" },
    { src: "/projects/05_MALL/YEKA/D5_Shot 2_20240405_134333.mp4", isVideo: true, fileName: "D5_Shot 2_20240405_134333.mp4" },
    ],
  },
  {
    id: "alliance",
    category: "06_OFFICE",
    categoryNumber: "06",
    title: "alliance",
    year: "2024",
    location: "Addis Ababa, ET",
    scale: "Office Tower",
    media: [
    { src: "/projects/06_OFFICE/alliance/Scene 8.webp", isVideo: false, fileName: "Scene 8.webp" },
    { src: "/projects/06_OFFICE/alliance/Scene 19.webp", isVideo: false, fileName: "Scene 19.webp" },
    { src: "/projects/06_OFFICE/alliance/Scene 20_2.webp", isVideo: false, fileName: "Scene 20_2.webp" },
    { src: "/projects/06_OFFICE/alliance/Scene 21_1.webp", isVideo: false, fileName: "Scene 21_1.webp" },
    { src: "/projects/06_OFFICE/alliance/Scene 22_4.webp", isVideo: false, fileName: "Scene 22_4.webp" },
    { src: "/projects/06_OFFICE/alliance/Scene 23_2.webp", isVideo: false, fileName: "Scene 23_2.webp" },
    { src: "/projects/06_OFFICE/alliance/Scene 24_2.webp", isVideo: false, fileName: "Scene 24_2.webp" },
    { src: "/projects/06_OFFICE/alliance/Scene 25_2.webp", isVideo: false, fileName: "Scene 25_2.webp" },
    { src: "/projects/06_OFFICE/alliance/Scene 26_2.webp", isVideo: false, fileName: "Scene 26_2.webp" },
    { src: "/projects/06_OFFICE/alliance/Scene 27_1.webp", isVideo: false, fileName: "Scene 27_1.webp" },
    { src: "/projects/06_OFFICE/alliance/Scene 27_2.webp", isVideo: false, fileName: "Scene 27_2.webp" },
    { src: "/projects/06_OFFICE/alliance/Scene 28_3.webp", isVideo: false, fileName: "Scene 28_3.webp" },
    { src: "/projects/06_OFFICE/alliance/Scene 29_1.webp", isVideo: false, fileName: "Scene 29_1.webp" },
    { src: "/projects/06_OFFICE/alliance/Scene 29_2.webp", isVideo: false, fileName: "Scene 29_2.webp" },
    ],
  },
  {
    id: "birhan-insurance",
    category: "06_OFFICE",
    categoryNumber: "06",
    title: "birhan insurance",
    year: "2024",
    location: "Addis Ababa, ET",
    scale: "Insurance HQ",
    media: [
    { src: "/projects/06_OFFICE/birhan insurance/Image.webp", isVideo: false, fileName: "Image.webp" },
    { src: "/projects/06_OFFICE/birhan insurance/Scene 5.webp", isVideo: false, fileName: "Scene 5.webp" },
    { src: "/projects/06_OFFICE/birhan insurance/Scene 6_1.webp", isVideo: false, fileName: "Scene 6_1.webp" },
    { src: "/projects/06_OFFICE/birhan insurance/Scene 9_2.webp", isVideo: false, fileName: "Scene 9_2.webp" },
    { src: "/projects/06_OFFICE/birhan insurance/Scene 11_1.webp", isVideo: false, fileName: "Scene 11_1.webp" },
    { src: "/projects/06_OFFICE/birhan insurance/Scene 12_1.webp", isVideo: false, fileName: "Scene 12_1.webp" },
    { src: "/projects/06_OFFICE/birhan insurance/Scene 12_style_transfer01.webp", isVideo: false, fileName: "Scene 12_style_transfer01.webp" },
    { src: "/projects/06_OFFICE/birhan insurance/Scene 14.webp", isVideo: false, fileName: "Scene 14.webp" },
    { src: "/projects/06_OFFICE/birhan insurance/Scene 15_1.webp", isVideo: false, fileName: "Scene 15_1.webp" },
    { src: "/projects/06_OFFICE/birhan insurance/Scene 16.webp", isVideo: false, fileName: "Scene 16.webp" },
    { src: "/projects/06_OFFICE/birhan insurance/Scene 17.webp", isVideo: false, fileName: "Scene 17.webp" },
    { src: "/projects/06_OFFICE/birhan insurance/Scene 18.webp", isVideo: false, fileName: "Scene 18.webp" },
    { src: "/projects/06_OFFICE/birhan insurance/Scene 20.webp", isVideo: false, fileName: "Scene 20.webp" },
    { src: "/projects/06_OFFICE/birhan insurance/Scene 21.webp", isVideo: false, fileName: "Scene 21.webp" },
    { src: "/projects/06_OFFICE/birhan insurance/Scene 22_1.webp", isVideo: false, fileName: "Scene 22_1.webp" },
    { src: "/projects/06_OFFICE/birhan insurance/Scene 22.webp", isVideo: false, fileName: "Scene 22.webp" },
    { src: "/projects/06_OFFICE/birhan insurance/Scene 23.webp", isVideo: false, fileName: "Scene 23.webp" },
    { src: "/projects/06_OFFICE/birhan insurance/Scene 24.webp", isVideo: false, fileName: "Scene 24.webp" },
    { src: "/projects/06_OFFICE/birhan insurance/Scene 26.webp", isVideo: false, fileName: "Scene 26.webp" },
    ],
  },
  {
    id: "dugda",
    category: "06_OFFICE",
    categoryNumber: "06",
    title: "dugda",
    year: "2024",
    location: "Ethiopia",
    scale: "Office Complex",
    media: [
    { src: "/projects/06_OFFICE/dugda/AREAL.mp4", isVideo: true, fileName: "AREAL.mp4" },
    { src: "/projects/06_OFFICE/dugda/NEW 1.mp4", isVideo: true, fileName: "NEW 1.mp4" },
    { src: "/projects/06_OFFICE/dugda/Scene 62.webp", isVideo: false, fileName: "Scene 62.webp" },
    { src: "/projects/06_OFFICE/dugda/Shot 2.mp4", isVideo: true, fileName: "Shot 2.mp4" },
    { src: "/projects/06_OFFICE/dugda/Shot 3.mp4", isVideo: true, fileName: "Shot 3.mp4" },
    { src: "/projects/06_OFFICE/dugda/Shot 5.mp4", isVideo: true, fileName: "Shot 5.mp4" },
    { src: "/projects/06_OFFICE/dugda/Shot 6(1).mp4", isVideo: true, fileName: "Shot 6(1).mp4" },
    { src: "/projects/06_OFFICE/dugda/Shot 7.mp4", isVideo: true, fileName: "Shot 7.mp4" },
    ],
  },
  {
    id: "mnrc-office",
    category: "06_OFFICE",
    categoryNumber: "06",
    title: "MNRC OFFICE",
    year: "2024",
    location: "Addis Ababa, ET",
    scale: "Office Tower Animation",
    media: [
    { src: "/projects/06_OFFICE/MNRC OFFICE/Shot 2.mp4", isVideo: true, fileName: "Shot 2.mp4" },
    { src: "/projects/06_OFFICE/MNRC OFFICE/Shot 3.mp4", isVideo: true, fileName: "Shot 3.mp4" },
    { src: "/projects/06_OFFICE/MNRC OFFICE/Shot 5.mp4", isVideo: true, fileName: "Shot 5.mp4" },
    { src: "/projects/06_OFFICE/MNRC OFFICE/Shot 6_1.mp4", isVideo: true, fileName: "Shot 6_1.mp4" },
    { src: "/projects/06_OFFICE/MNRC OFFICE/Shot 7_1.mp4", isVideo: true, fileName: "Shot 7_1.mp4" },
    { src: "/projects/06_OFFICE/MNRC OFFICE/Shot 8_1.mp4", isVideo: true, fileName: "Shot 8_1.mp4" },
    ],
  },
  {
    id: "op-1",
    category: "06_OFFICE",
    categoryNumber: "06",
    title: "OP 1",
    year: "2024",
    location: "Addis Ababa, ET",
    scale: "Office Project 1",
    media: [
    { src: "/projects/06_OFFICE/OP 1/Scene 25.webp", isVideo: false, fileName: "Scene 25.webp" },
    { src: "/projects/06_OFFICE/OP 1/Scene 28.webp", isVideo: false, fileName: "Scene 28.webp" },
    { src: "/projects/06_OFFICE/OP 1/Scene 29.webp", isVideo: false, fileName: "Scene 29.webp" },
    { src: "/projects/06_OFFICE/OP 1/Scene 30.webp", isVideo: false, fileName: "Scene 30.webp" },
    { src: "/projects/06_OFFICE/OP 1/Scene 31.webp", isVideo: false, fileName: "Scene 31.webp" },
    { src: "/projects/06_OFFICE/OP 1/Scene 32.webp", isVideo: false, fileName: "Scene 32.webp" },
    { src: "/projects/06_OFFICE/OP 1/Scene 33.webp", isVideo: false, fileName: "Scene 33.webp" },
    { src: "/projects/06_OFFICE/OP 1/Scene 34.webp", isVideo: false, fileName: "Scene 34.webp" },
    { src: "/projects/06_OFFICE/OP 1/Scene 35.webp", isVideo: false, fileName: "Scene 35.webp" },
    ],
  },
  {
    id: "op2",
    category: "06_OFFICE",
    categoryNumber: "06",
    title: "OP2",
    year: "2024",
    location: "Addis Ababa, ET",
    scale: "Office Project 2",
    media: [
    { src: "/projects/06_OFFICE/OP2/Clip 1.mp4", isVideo: true, fileName: "Clip 1.mp4" },
    { src: "/projects/06_OFFICE/OP2/Clip 2.mp4", isVideo: true, fileName: "Clip 2.mp4" },
    { src: "/projects/06_OFFICE/OP2/Clip 3.mp4", isVideo: true, fileName: "Clip 3.mp4" },
    { src: "/projects/06_OFFICE/OP2/Clip 4.mp4", isVideo: true, fileName: "Clip 4.mp4" },
    { src: "/projects/06_OFFICE/OP2/Clip 5.mp4", isVideo: true, fileName: "Clip 5.mp4" },
    { src: "/projects/06_OFFICE/OP2/image-e1nhanced.webp", isVideo: false, fileName: "image-e1nhanced.webp" },
    { src: "/projects/06_OFFICE/OP2/image-enhanced.webp", isVideo: false, fileName: "image-enhanced.webp" },
    { src: "/projects/06_OFFICE/OP2/Scene 2_1.webp", isVideo: false, fileName: "Scene 2_1.webp" },
    { src: "/projects/06_OFFICE/OP2/Scene 6.webp", isVideo: false, fileName: "Scene 6.webp" },
    { src: "/projects/06_OFFICE/OP2/Scene 16.webp", isVideo: false, fileName: "Scene 16.webp" },
    { src: "/projects/06_OFFICE/OP2/Scene 17_1.webp", isVideo: false, fileName: "Scene 17_1.webp" },
    { src: "/projects/06_OFFICE/OP2/Scene 18.webp", isVideo: false, fileName: "Scene 18.webp" },
    { src: "/projects/06_OFFICE/OP2/Scene 19_1.webp", isVideo: false, fileName: "Scene 19_1.webp" },
    { src: "/projects/06_OFFICE/OP2/Scene 21_1.webp", isVideo: false, fileName: "Scene 21_1.webp" },
    { src: "/projects/06_OFFICE/OP2/Scene 22.webp", isVideo: false, fileName: "Scene 22.webp" },
    { src: "/projects/06_OFFICE/OP2/Scene 24_1.webp", isVideo: false, fileName: "Scene 24_1.webp" },
    ],
  },
  {
    id: "adiya",
    category: "07_RESDENCE",
    categoryNumber: "07",
    title: "ADIYA",
    year: "2024",
    location: "Addis Ababa, ET",
    scale: "Private Residence",
    media: [
    { src: "/projects/07_RESDENCE/ADIYA/Scene 5.webp", isVideo: false, fileName: "Scene 5.webp" },
    { src: "/projects/07_RESDENCE/ADIYA/Scene 6.webp", isVideo: false, fileName: "Scene 6.webp" },
    { src: "/projects/07_RESDENCE/ADIYA/Scene 7_1.webp", isVideo: false, fileName: "Scene 7_1.webp" },
    { src: "/projects/07_RESDENCE/ADIYA/Scene 9.webp", isVideo: false, fileName: "Scene 9.webp" },
    { src: "/projects/07_RESDENCE/ADIYA/Scene 10.webp", isVideo: false, fileName: "Scene 10.webp" },
    { src: "/projects/07_RESDENCE/ADIYA/Scene 11.webp", isVideo: false, fileName: "Scene 11.webp" },
    { src: "/projects/07_RESDENCE/ADIYA/Scene 34.webp", isVideo: false, fileName: "Scene 34.webp" },
    { src: "/projects/07_RESDENCE/ADIYA/Scene 36.webp", isVideo: false, fileName: "Scene 36.webp" },
    ],
  },
  {
    id: "aster",
    category: "07_RESDENCE",
    categoryNumber: "07",
    title: "ASTER",
    year: "2024",
    location: "Addis Ababa, ET",
    scale: "Private Residence",
    media: [
    { src: "/projects/07_RESDENCE/ASTER/Scene 51.webp", isVideo: false, fileName: "Scene 51.webp" },
    { src: "/projects/07_RESDENCE/ASTER/Scene 52.webp", isVideo: false, fileName: "Scene 52.webp" },
    ],
  },
  {
    id: "rozina",
    category: "07_RESDENCE",
    categoryNumber: "07",
    title: "ROZINA",
    year: "2024",
    location: "Addis Ababa, ET",
    scale: "Private Residence",
    media: [
    { src: "/projects/07_RESDENCE/ROZINA/01 (16).webp", isVideo: false, fileName: "01 (16).webp" },
    { src: "/projects/07_RESDENCE/ROZINA/01 (17).webp", isVideo: false, fileName: "01 (17).webp" },
    { src: "/projects/07_RESDENCE/ROZINA/01 (18).webp", isVideo: false, fileName: "01 (18).webp" },
    { src: "/projects/07_RESDENCE/ROZINA/01 (19).webp", isVideo: false, fileName: "01 (19).webp" },
    { src: "/projects/07_RESDENCE/ROZINA/01 (20).webp", isVideo: false, fileName: "01 (20).webp" },
    { src: "/projects/07_RESDENCE/ROZINA/01 (21).webp", isVideo: false, fileName: "01 (21).webp" },
    { src: "/projects/07_RESDENCE/ROZINA/01 (22).webp", isVideo: false, fileName: "01 (22).webp" },
    { src: "/projects/07_RESDENCE/ROZINA/01 (24).webp", isVideo: false, fileName: "01 (24).webp" },
    { src: "/projects/07_RESDENCE/ROZINA/01 (26).webp", isVideo: false, fileName: "01 (26).webp" },
    { src: "/projects/07_RESDENCE/ROZINA/01 (27).webp", isVideo: false, fileName: "01 (27).webp" },
    { src: "/projects/07_RESDENCE/ROZINA/01 (30).webp", isVideo: false, fileName: "01 (30).webp" },
    { src: "/projects/07_RESDENCE/ROZINA/01 (31).webp", isVideo: false, fileName: "01 (31).webp" },
    { src: "/projects/07_RESDENCE/ROZINA/01 (32).webp", isVideo: false, fileName: "01 (32).webp" },
    { src: "/projects/07_RESDENCE/ROZINA/01 (34).webp", isVideo: false, fileName: "01 (34).webp" },
    { src: "/projects/07_RESDENCE/ROZINA/photo_6003679379009422639_y.webp", isVideo: false, fileName: "photo_6003679379009422639_y.webp" },
    { src: "/projects/07_RESDENCE/ROZINA/Scene 89.webp", isVideo: false, fileName: "Scene 89.webp" },
    { src: "/projects/07_RESDENCE/ROZINA/Scene 90.webp", isVideo: false, fileName: "Scene 90.webp" },
    ],
  },
  {
    id: "legetafo-landscape",
    category: "08_LANDSCAPE",
    categoryNumber: "08",
    title: "LEGETAFO LANDSCAPE",
    year: "2024",
    location: "Legetafo, ET",
    scale: "Landscape Masterplan",
    media: [
    { src: "/projects/08_LANDSCAPE/LEGETAFO LANDSCAPE/11.webp", isVideo: false, fileName: "11.webp" },
    { src: "/projects/08_LANDSCAPE/LEGETAFO LANDSCAPE/12.webp", isVideo: false, fileName: "12.webp" },
    { src: "/projects/08_LANDSCAPE/LEGETAFO LANDSCAPE/21.webp", isVideo: false, fileName: "21.webp" },
    { src: "/projects/08_LANDSCAPE/LEGETAFO LANDSCAPE/22.webp", isVideo: false, fileName: "22.webp" },
    { src: "/projects/08_LANDSCAPE/LEGETAFO LANDSCAPE/41.webp", isVideo: false, fileName: "41.webp" },
    { src: "/projects/08_LANDSCAPE/LEGETAFO LANDSCAPE/42.webp", isVideo: false, fileName: "42.webp" },
    { src: "/projects/08_LANDSCAPE/LEGETAFO LANDSCAPE/FLY_10.mp4", isVideo: true, fileName: "FLY_10.mp4" },
    { src: "/projects/08_LANDSCAPE/LEGETAFO LANDSCAPE/Shot 1_1.mp4", isVideo: true, fileName: "Shot 1_1.mp4" },
    { src: "/projects/08_LANDSCAPE/LEGETAFO LANDSCAPE/Shot 1.mp4", isVideo: true, fileName: "Shot 1.mp4" },
    { src: "/projects/08_LANDSCAPE/LEGETAFO LANDSCAPE/Shot 1(1).mp4", isVideo: true, fileName: "Shot 1(1).mp4" },
    { src: "/projects/08_LANDSCAPE/LEGETAFO LANDSCAPE/Shot 2(2).mp4", isVideo: true, fileName: "Shot 2(2).mp4" },
    { src: "/projects/08_LANDSCAPE/LEGETAFO LANDSCAPE/Shot 9_2.mp4", isVideo: true, fileName: "Shot 9_2.mp4" },
    { src: "/projects/08_LANDSCAPE/LEGETAFO LANDSCAPE/Shot 9_3.mp4", isVideo: true, fileName: "Shot 9_3.mp4" },
    { src: "/projects/08_LANDSCAPE/LEGETAFO LANDSCAPE/Shot 10_1.mp4", isVideo: true, fileName: "Shot 10_1.mp4" },
    { src: "/projects/08_LANDSCAPE/LEGETAFO LANDSCAPE/Shot 10.mp4", isVideo: true, fileName: "Shot 10.mp4" },
    ],
  },
  {
    id: "hospital",
    category: "09_PROPOSAL",
    categoryNumber: "09",
    title: "HOSPITAL",
    year: "2023",
    location: "Ethiopia",
    scale: "Healthcare Proposal",
    media: [
    { src: "/projects/09_PROPOSAL/HOSPITAL/01 (2).webp", isVideo: false, fileName: "01 (2).webp" },
    { src: "/projects/09_PROPOSAL/HOSPITAL/01 (12).webp", isVideo: false, fileName: "01 (12).webp" },
    { src: "/projects/09_PROPOSAL/HOSPITAL/01 (13).webp", isVideo: false, fileName: "01 (13).webp" },
    ],
  },
  {
    id: "yeka-park",
    category: "09_PROPOSAL",
    categoryNumber: "09",
    title: "YEKA PARK",
    year: "2023",
    location: "Addis Ababa, ET",
    scale: "Park Proposal",
    media: [
    { src: "/projects/09_PROPOSAL/YEKA PARK/01 (8).webp", isVideo: false, fileName: "01 (8).webp" },
    ],
  },
  {
    id: "bilos",
    category: "11_CAFE ANDRESTAURANT",
    categoryNumber: "11",
    title: "BILOS",
    year: "2024",
    location: "Addis Ababa, ET",
    scale: "Cafe & Restaurant Animation",
    media: [
    { src: "/projects/11_CAFE ANDRESTAURANT/BILOS/D5_Shot 38_20231224_173624.mp4", isVideo: true, fileName: "D5_Shot 38_20231224_173624.mp4" },
    { src: "/projects/11_CAFE ANDRESTAURANT/BILOS/D5_Shot 40_20231224_180357.mp4", isVideo: true, fileName: "D5_Shot 40_20231224_180357.mp4" },
    { src: "/projects/11_CAFE ANDRESTAURANT/BILOS/D5_Shot 41_20231224_172006.mp4", isVideo: true, fileName: "D5_Shot 41_20231224_172006.mp4" },
    { src: "/projects/11_CAFE ANDRESTAURANT/BILOS/Shot 2.mp4", isVideo: true, fileName: "Shot 2.mp4" },
    { src: "/projects/11_CAFE ANDRESTAURANT/BILOS/Shot 4_1.mp4", isVideo: true, fileName: "Shot 4_1.mp4" },
    { src: "/projects/11_CAFE ANDRESTAURANT/BILOS/Shot 4.mp4", isVideo: true, fileName: "Shot 4.mp4" },
    { src: "/projects/11_CAFE ANDRESTAURANT/BILOS/Shot 5.mp4", isVideo: true, fileName: "Shot 5.mp4" },
    ],
  },
];

export function posterFor(p: Project): MediaItem | undefined {
  return p.media.find((m) => !m.isVideo) ?? p.media[0];
}
